version: '3.7'

services:
  fpswagger:
    build:
      context: .
      dockerfile: server2/Dockerfile
    ports:
      - "9090:9090"
    environment:
      NODE_ENV: development
      AZURE_APP_CLIENT_ID: local-swagger
      AZURE_APP_JWKS: |
        {"keys":[
          {
            "p": "uglj69HBqwsI8HoRZ3O3LZLagL4LASooVJktgCvTgjucVDovIYeSSUmd1LTtDKFM2W-oobbWQA-t1-pnTM0dnEgti0d3fWuiBe1StAoiCSh18KOcnMnors-MQi-WlmBUACGRYX2v0coMCLWMBkMfRjPGZ43eHutCcyRydNCopOE",
            "kty": "RSA",
            "q": "s1uYe4HX1HHKbVlmHbHsGjiMown3Qio0KYO8ehohVbkH9-2lFpb00h2-NZMXZxluBBWmx5ukIV07NJ9nKiFbRTkR2b2ww5WocPYRk4fAMYDe8sCHOHuOAZiI6F97x4kySPiqj_U2ut_EWkgDtUkMwtciZDzwRmcuGPb-c8OHSkU",
            "d": "CGME29GzZxGC7CcqfiWabszarqXfCFLBkVD6cQqYBilA3DJ-3j3_txIWaQVtUplBQt6YOIL8S_-4D_LGFn5B4bHYq5pPLsV6FJfqYLz2CRppWH5cvQYqH1MraOSm0127vG19KRDK02FUC77P7X9gFiOPLerU8j02mhu6riQmfvT8fRZ3It8yN_RL0aaQ87m_acI33pS5lUhR8ooaWBKN27pWeiVMImMJ4OxiPZiU-9C8rbLwFjiXjZzjuxmWQ7zu1-aqfy4iqc4kyFLo6H6wIY3mGgK76k3zmQrerJRTZElAzm6018IWNLNkVJKjsaH5GwSmK0KVnZLj6NPrbWzvgQ",
            "e": "AQAB",
            "use": "sig",
            "kid": "azureAd",
            "qi": "g87KpFNEigeOQ2EF6hdjllzmyYu3rVIUvqKTR7RjiqDQwujRlugGbXGXxJy93X5FLpk6Z2xM-cwE2PEm1369ZZxom3EDx46sic1v5aH9mbU2BhaGOfpY4Mi9X72VkW_KBMoAfJYPi3SCScBMoqYkAOFGbtS3uARvY0-HB0P5X2U",
            "dp": "GmTOqlxeD7hHEmcfJQBD0tFs8qsDwKyMgEQjMnYFUgrHCSQgH6-uT3uESvNIVmxkDM1MrXTVPM18qo91DG5lbxDGdWY0S7UDjbe37hcp8QauhO-RfqUev_5uNc2unbMY99PLXnuIgEkcH_gx34mSXFFoKrTz-IsEKHXZTz1zT8E",
            "dq": "Zy48bGDoDxlfQMT7T_35O6Rok6q6CeBJndBhb0T1BGGryd9256X0NaRStnNmNTOV7Nef2JkbNO5zjvRc3wnNfec087SCqiHAgyusNNkVoeTnXXOQ1teNfDGKIVQ82y98NCqJxMNmtt7gEKf5KiNaKgSljlDYUUguZsJA48wKWpk",
            "n": "glchA7ywlOiBhxPj6WxGcbiT2ejpfVivkWz0KdQ8BiXxZaUBMr4hdB6voYfSWaNaZle6Avy10MVr-hn8Ef15G1y4ot_vEVdomhLBsaX1UcyMSY8J-rZusq1sPmkBZbe0Xoivt__AJaXBS2OZi8PgCe80HYEN2G3PB3ytvA8YC99l3xBzTmYlSWCth9mJiR4ovlQdsswu7ruDNCrtO2MktLrFehKkha3LFiZiq0MTaXzK2XyvgjwU8o12pyWpVnmF8vttY2mQln8C5_ybTxT1C62e2Q0QR9K25t3YY6qeDjsD0SypaxCtfiQ5dwidorwTi1mKKaz_5AuAAmtmUsR6pQ",
            "alg": "RS256"
          }
        ]}
      AZURE_APP_WELL_KNOWN_URL: http://host.docker.internal:8080/azureAd/.well-known/openid-configuration
      PROXY_CONFIG: | 
        {"apis":[
          {"path":"/fpsak/api","url":"http://192.168.5.2:8081/fpsak/api/openapi.json","scopes":"api://fpsak/.default","name":"fpsak"}
        ]}
      PORT: 9090
    container_name: fpswagger
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/isReady" ]
      interval: 15s
      timeout: 10s
      retries: 10
    links:
      - mock-oauth2-server

## MÃ¥ bruke vtp oppsett
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.1
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/default/.well-known/openid-configuration" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      JSON_CONFIG: |
        {
          "interactiveLogin": true,
          "httpServer": "NettyWrapper",
          "tokenCallbacks": [
            {
              "issuerId": "azureAd",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "grant_type",
                  "match": "authorization_code",
                  "claims": {
                    "sub": "saksbeh",
                    "sid": "1234"
                  }
                }
              ]
            }
          ]
        }
    hostname: host.docker.internal
